version: 2.1

jobs:
  build:
    docker:
      - image: circleci/rust:1.55
    steps:
      - checkout
      - run:
          name: "Compile"
          command: "cargo build --release"
  test:
    docker:
      - image: circleci/rust:1.55
    steps:
      - checkout
      - run:
          name: "Test"
          command: "cargo test"
  document:
    docker:
      - image: circleci/rust:1.55
    steps:
      - checkout
      - run:
          name: "Document"
          command: "cargo doc"

workflows:
  build-workflow:
    jobs:
      - test
      - build:
          requires:
            - test
          path: target/release
      - document:
          requires:
            - test
