version: 2.1

jobs:
  build:
    docker:
      - image: circleci/rust:1.55
    steps:
      - checkout
      - run:
          name: "Compile"
          command: "cargo build --release"
      - store_artifacts:
          path: target/release
  test:
    docker:
      - image: circleci/rust:1.55
    steps:
      - checkout
      - run:
          name: "Test"
          command: "cargo test"

workflows:
  build-workflow:
    jobs:
      - test
      - build:
          requires:
            - test
